name: vocapp
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+3
  path: ^1.8.0
  provider: ^6.0.3
  form_field_validator: ^1.1.0
  google_fonts: ^2.1.0 # to use google fonts
  shared_preferences: ^2.0.7
  percent_indicator: ^4.0.1
  json_annotation: ^4.4.0
  auto_route: ^5.0.1
  path_provider: ^2.0.11
  local_value: ^1.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.1
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  analyzer:

flutter_native_splash:
  background_image: "assets/images/app_bg.png"
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/auth/
    - assets/images/icons/
  # do a hot restart after adding new image directory
  fonts:
    - family: Klasik
      fonts:
        - asset: assets/fonts/Klasik Regular.otf
